language: scala
scala:
   - 2.12.8
jdk:
  - openjdk11

stages:
  - crosscompile
  - test

jobs:
  include:
    - stage: crosscompile
      script: sbt +clean +test
    - stage: test
      script: sbt clean coverage test coverageReport coverageAggregate codacyCoverage